# Generated by Django 4.2.10 on 2024-02-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjob',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Logistics.vehicle'),
        ),
    ]
